
SCENE_CHANNEL = 3

SCREEN_WIDTH = 64
SCREEN_HEIGHT = 96

PLAYER_WIDTH = 4
PLAYER_HEIGHT = 4

EMULATOR_RENDER_MAGNIFICATION = 5
RENDER_WIDTH = SCREEN_WIDTH * EMULATOR_RENDER_MAGNIFICATION
RENDER_HEIGHT = SCREEN_HEIGHT * EMULATOR_RENDER_MAGNIFICATION

LEFT, RIGHT, UP, DOWN, FIRE = 0, 1, 2, 3, 4

